CREATE FUNCTION staging_patent_clusters.checkLanguages(langs ANY TYPE) 
RETURNS BOOLEAN 
AS (
  'multilingual' IN UNNEST(langs)
  OR 'ar' IN UNNEST(langs)
  OR 'bg' IN UNNEST(langs)
  OR 'ca' IN UNNEST(langs)
  OR 'cs' IN UNNEST(langs)
  OR 'da' IN UNNEST(langs)
  OR 'de' IN UNNEST(langs)
  OR 'el' IN UNNEST(langs)
  OR 'en' IN UNNEST(langs)
  OR 'es' IN UNNEST(langs)
  OR 'et' IN UNNEST(langs)
  OR 'fa' IN UNNEST(langs)
  OR 'fi' IN UNNEST(langs)
  OR 'fr' IN UNNEST(langs)
  OR 'gl' IN UNNEST(langs)
  OR 'gu' IN UNNEST(langs)
  OR 'he' IN UNNEST(langs)
  OR 'hi' IN UNNEST(langs)
  OR 'hr' IN UNNEST(langs)
  OR 'hu' IN UNNEST(langs)
  OR 'hy' IN UNNEST(langs)
  OR 'id' IN UNNEST(langs)
  OR 'it' IN UNNEST(langs)
  OR 'ja' IN UNNEST(langs)
  OR 'ka' IN UNNEST(langs)
  OR 'ko' IN UNNEST(langs)
  OR 'ku' IN UNNEST(langs)
  OR 'lt' IN UNNEST(langs)
  OR 'lv' IN UNNEST(langs)
  OR 'mk' IN UNNEST(langs)
  OR 'mn' IN UNNEST(langs)
  OR 'mr' IN UNNEST(langs)
  OR 'ms' IN UNNEST(langs)
  OR 'my' IN UNNEST(langs)
  OR 'nb' IN UNNEST(langs)
  OR 'nl' IN UNNEST(langs)
  OR 'pl' IN UNNEST(langs)
  OR 'pt' IN UNNEST(langs)
  OR 'ro' IN UNNEST(langs)
  OR 'ru' IN UNNEST(langs)
  OR 'sk' IN UNNEST(langs)
  OR 'sl' IN UNNEST(langs)
  OR 'sq' IN UNNEST(langs)
  OR 'sr' IN UNNEST(langs)
  OR 'sv' IN UNNEST(langs)
  OR 'th' IN UNNEST(langs)
  OR 'tr' IN UNNEST(langs)
  OR 'uk' IN UNNEST(langs)
  OR 'ur' IN UNNEST(langs)
  OR 'vi' IN UNNEST(langs)
  OR 'zh' IN UNNEST(langs)
  OR 'fr-ca' IN UNNEST(langs)
  OR 'pt-br' IN UNNEST(langs)
  OR 'zh-tw' IN UNNEST(langs)
); 